version: "2"
services:
  web:
    build: .
    environment:
     - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"